### ISSUE TITLE
# 프로젝트 콘솔페이지 초기화면 에서의 문제

### ISSUE THREAD

**Issue by Yanguk** [Team-TTT/Circle-Web-FE#13]
#12 

<img width="1809" alt="image" src="https://user-images.githubusercontent.com/99335782/197831604-6ecffffe-50e2-4245-abc4-6e9c0495a6bc.png">

<img width="1809" alt="image" src="https://user-images.githubusercontent.com/99335782/197831947-264092e3-80a4-4223-9692-5422f9c9c2e3.png">

초기화면에서 채널가기 버튼을 누를시 채널페이지에서 에러나옴
추후 리팩토링 필요 
ex) 빈화면 보여주기

**Comment by ssong-yi** [comment]
어떤 에러가 나오나요??

**Comment by Yanguk** [comment]
기존 로직이 params로 들어온 프로젝트아이디를 활용해서 데이터를 뿌리는데 이상한값이 들어오면서 에러가 났습니다.
분기처리하여서 console/project 경로로 다시 네비게이트 시키는 형식으로 수정하였습니다
